"""Adiciona campo site ao modelo Projeto

Revision ID: 1b20e38f88ad
Revises: b6e952393187
Create Date: 2025-05-06 19:46:03.614666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b20e38f88ad'
down_revision = 'b6e952393187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_column('site')

    # ### end Alembic commands ###
